---
- name: Install runner-helper images package
  ansible.builtin.apt:
    deb: >-
      https://gitlab-runner-downloads.s3.amazonaws.com/v{{- gitlab_runner_version -}}
      /deb/gitlab-runner-helper-images.deb
    state: present
  register: result
  until: result is succeeded
  retries: 10
  delay: 10

- name: Install gitlab-runner
  ansible.builtin.apt:
    deb: >-
      https://gitlab-runner-downloads.s3.amazonaws.com/v{{- gitlab_runner_version -}}
      /deb/gitlab-runner_{{- architecture[ansible_architecture] -}}.deb
    state: present
  register: result
  until: result is succeeded
  retries: 10
  delay: 10

- name: Install required packages
  ansible.builtin.apt:
    update_cache: true
    name:
      - acl
      - ca-certificates
      - curl
      - unzip
      - amazon-ecr-credential-helper
    state: present
  register: result
  until: result is succeeded
  retries: 10
  delay: 10

- name: Add apt key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add deb repo
  ansible.builtin.copy:
    content: >-
      deb [arch={{ architecture[ansible_architecture] }} signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    dest: /etc/apt/sources.list.d/docker.list
    mode: '0644'

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install Docker and related packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Install python3-pip
  ansible.builtin.apt:
    name:
      - python3-pip
    state: present

- name: Download AWS CLI v2 installer
  ansible.builtin.get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip
    mode: '0644'

- name: Unzip AWS CLI v2 installer
  ansible.builtin.unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp
    remote_src: true
    creates: /tmp/aws

- name: Install (or update) AWS CLI v2
  ansible.builtin.command: /tmp/aws/install --update
  args:
    creates: /usr/local/bin/aws
